new: usr: Add add_routine() function to add Function & StoredProcedure object to an Entity [FLYCS-985]
Fourcast/flycs_sdk pull request #37
Opened 2022-05-19 09:58 UTC by yannis-arg

2022-05-19 11:30 UTC, zaibon requested changes

2022-05-19 11:30 UTC, zaibon commented on flycs_sdk/entities.py
> +        """Insert a View into the stage_config of the entity.
```suggestion
        """Insert a Function or Procedure into the stage_config of the entity.
```

2022-05-19 11:30 UTC, zaibon commented on flycs_sdk/entities.py
> +        :param stage: the name of the stage where to insert the transformation
```suggestion
        :param stage: the name of the stage where to insert the object
```

2022-05-20 07:35 UTC, christophedcpm approved these changes
LGTM

2022-05-20 07:36 UTC, merged